permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# 作者信息
author: 
  name: Forrest Hu
  email: 
  link: 
  weibo: 
  github: https://forresthu.github.io

# 站点信息
title: Forrest Hu's Blogs
description: Forrest Hu's blogs
url: https://forresthu.github.io
rss_url: 

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.jpg
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
# google_analytics_tracking_id:
# ga:
#   id: UA-108442533-1
#   url: 

# disqus 设置
# disqus:
#   shortname: qiankunli

# gitment
# gitment:
#   id: ddbaadab5f5d810805c3
#   secret: 13b91b306680f11a55713382529b83259ef56546

# 主题设置，自动激活某个标签
active: 技术

plugins:
- jekyll-paginate
- jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      render_with_liquid: false
      usemathjax: true